### ISSUE TITLE
Course Module

### ISSUE THREAD

**Issue by YashKumarVerma** [commclassroom/commclassroomBackend#16]
course module details with all operations related to courses across the services. 

## How to track and work 
the items that are complete have the box checked. This issue is marked as an *epic* which means it would act as a parent issue for other issues.

Interested in working? Create an issue (mention `feature request` in the issue title) and comment on your issue link as a reply to this issue. One of the moderators would assign you the issue, and you can then start working.  

## Routes - exposed to users
- [ ] Create a new course
- [ ] Update the details of an existing course
- [ ] Delete a course
- [ ] Get details of particular course
- [ ] Get list of all courses (paginated)
- [ ] Search for a course
    - [ ] based on string matching 
    - [ ] based on rating
    - [ ] based on number of enrollments
    - [ ] based on featured / non featured flag
    - [ ] based on tags (example: `app`, `web dev`, `dsa`)

## Service functions - defined in the system for internal usage
- [ ] To create a new course
- [ ] To get all details of a course by id
- [ ] To get short details (name, enrollments, rating) of a course by id
- [ ] To update the details of a course
- [ ] To delete a course
- [ ] Search for a course
    - [ ] based on string matching 
    - [ ] based on rating
    - [ ] based on number of enrollments
    - [ ] based on featured / non featured flag
    - [ ] based on tags (example: `app`, `web dev`, `dsa`)

**Comment by Udit-takkar** [comment]
is there any discord/whatsapp group for contributors so that we can discuss  ? I also want to join this

**Comment by AvineshTripathi** [comment]
@Udit-takkar  https://discord.gg/uhZfYvZ5 here is our community classroom discord link you can surly say us hii there and work together

**Comment by Mohit-Swain** [comment]
Please have a look at #30

**Comment by tejaswini22199** [comment]
Hi, I would like to work on issue #31  .

**Comment by YashKumarVerma** [comment]
Child Issues : 

- [ ] https://github.com/commclassroom/commclassroomBackend/issues/30 - @Mohit-Swain 
- [ ] https://github.com/commclassroom/commclassroomBackend/issues/31 @tejaswini22199

**Comment by Zain-Muiz** [comment]
Heyy @YashKumarVerma , Created Issue to cover the remaining sections --> #34 .
